# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  example:
    cmd: go run examples/{{.CLI_ARGS}}/main.go
  test:
    desc: Run all tests
    silent: true
    cmd: go test ./... -race
